import type { components } from "./schema";

export type ErrorResponse = components["schemas"]["ErrorResponse"];
export type LoginRequest = components["schemas"]["LoginRequest"];
export type LoginResponse = components["schemas"]["LoginResponse"];
export type SessionResponse = components["schemas"]["SessionResponse"];
export type ProjectResponse = components["schemas"]["ProjectResponse"];
export type ProjectListResponse = components["schemas"]["ProjectListResponse"];
export type LogicalProjectResponse = components["schemas"]["LogicalProjectResponse"];
export type LogicalProjectListResponse = components["schemas"]["LogicalProjectListResponse"];
export type LogicalProjectCreateRequest = components["schemas"]["LogicalProjectCreateRequest"];
export type DeviceMetadataResponse = components["schemas"]["DeviceMetadataResponse"];
export type DeviceListResponse = components["schemas"]["DeviceListResponse"];
export type PairingChallengeResponse = components["schemas"]["PairingChallengeResponse"];
export type DeviceEnrollmentRequest = components["schemas"]["DeviceEnrollmentRequest"];
export type WorkspaceBindingResponse = components["schemas"]["WorkspaceBindingResponse"];
export type WorkspaceBindingListResponse = components["schemas"]["WorkspaceBindingListResponse"];
export type WorkspaceBindingCreateRequest = components["schemas"]["WorkspaceBindingCreateRequest"];
export type SnapshotUploadBeginRequest = components["schemas"]["SnapshotUploadBeginRequest"];
export type SnapshotFileManifest = components["schemas"]["SnapshotFileManifest"];
export type SnapshotResponse = components["schemas"]["SnapshotResponse"];
export type SnapshotListResponse = components["schemas"]["SnapshotListResponse"];
export type SnapshotUploadResponse = components["schemas"]["SnapshotUploadResponse"];
export type TaskContractResponse = components["schemas"]["TaskContractResponse"];
export type TaskListResponse = components["schemas"]["TaskListResponse"];
export type ExecutionTargetStatusResponse = components["schemas"]["ExecutionTargetStatusResponse"];
export type MemoryAssociationPreviewResponse = components["schemas"]["MemoryAssociationPreviewResponse"];
