return function(p)
  vim.o.background = p.dark and 'dark' or 'light'
  local h = {
    Normal = { fg = p.foreground, bg = p.background },
    NormalFloat = { fg = p.foreground, bg = p.surface },
    FloatBorder = { fg = p.primary, bg = p.surface },
    Cursor = { fg = p.background, bg = p.primary },
    CursorLine = { bg = p.surface },
    LineNr = { fg = p.accent },
    CursorLineNr = { fg = p.primary, bold = true },
    SignColumn = { fg = p.foreground, bg = p.background },
    FoldColumn = { fg = p.accent, bg = p.background },
    Folded = { fg = p.foreground, bg = p.surface },
    WinSeparator = { fg = p.primary },
    EndOfBuffer = { fg = p.surface },
    NonText = { fg = p.accent },
    Whitespace = { fg = p.accent },
    SpecialKey = { fg = p.accent },
    MsgArea = { fg = p.foreground, bg = p.background },
    ErrorMsg = { fg = p.error },
    WarningMsg = { fg = p.warning },
    Title = { fg = p.primary, bold = true },
    Directory = { fg = p.primary },
    Question = { fg = p.success },
    MoreMsg = { fg = p.success },
    MatchParen = { fg = p.background, bg = p.accent },
    DiffAdd = { fg = p.success, bg = p.surface },
    DiffChange = { fg = p.warning, bg = p.surface },
    DiffDelete = { fg = p.error, bg = p.surface },
    DiffText = { fg = p.background, bg = p.warning },
    SpellBad = { sp = p.error, undercurl = true },
    SpellCap = { sp = p.warning, undercurl = true },
    SpellLocal = { sp = p.primary, undercurl = true },
    SpellRare = { sp = p.accent, undercurl = true },
    Visual = { fg = p.foreground, bg = p.panel },
    Search = { fg = p.background, bg = p.warning },
    IncSearch = { fg = p.background, bg = p.primary },
    Comment = { fg = p.accent, italic = true },
    String = { fg = p.success },
    Number = { fg = p.secondary },
    Constant = { fg = p.secondary },
    Identifier = { fg = p.foreground },
    Function = { fg = p.primary },
    Statement = { fg = p.secondary },
    Type = { fg = p.primary },
    Special = { fg = p.accent },
    PreProc = { fg = p.warning },
    Error = { fg = p.error },
    Pmenu = { fg = p.foreground, bg = p.surface },
    PmenuSel = { fg = p.background, bg = p.primary },
    PmenuSbar = { bg = p.panel },
    PmenuThumb = { bg = p.primary },
    WildMenu = { fg = p.background, bg = p.primary },
    StatusLine = { fg = p.foreground, bg = p.panel },
    StatusLineNC = { fg = p.foreground, bg = p.surface },
    TabLine = { fg = p.foreground, bg = p.surface },
    TabLineSel = { fg = p.background, bg = p.primary },
    TabLineFill = { bg = p.background },
    DiagnosticError = { fg = p.error },
    DiagnosticWarn = { fg = p.warning },
    DiagnosticInfo = { fg = p.primary },
    DiagnosticHint = { fg = p.accent },
    MiniStatuslineModeNormal = { fg = p.background, bg = p.primary },
    MiniStatuslineModeInsert = { fg = p.background, bg = p.success },
    MiniStatuslineModeVisual = { fg = p.background, bg = p.secondary },
    MiniStatuslineModeReplace = { fg = p.background, bg = p.error },
    MiniStatuslineModeCommand = { fg = p.background, bg = p.warning },
    MiniStatuslineModeOther = { fg = p.foreground, bg = p.panel },
    MiniStatuslineDevinfo = { fg = p.foreground, bg = p.surface },
    MiniStatuslineFilename = { fg = p.foreground, bg = p.panel },
    MiniStatuslineFileinfo = { fg = p.foreground, bg = p.surface },
    MiniStatuslineInactive = { fg = p.foreground, bg = p.surface },
    MiniTablineCurrent = { fg = p.background, bg = p.primary },
    MiniTablineVisible = { fg = p.foreground, bg = p.panel },
    MiniTablineHidden = { fg = p.foreground, bg = p.surface },
    MiniTablineModifiedCurrent = { fg = p.background, bg = p.warning },
    MiniTablineModifiedVisible = { fg = p.warning, bg = p.panel },
    MiniTablineModifiedHidden = { fg = p.warning, bg = p.surface },
    MiniTablineFill = { bg = p.background },
  }
  for name, value in pairs(h) do
    vim.api.nvim_set_hl(0, name, value)
  end
  local colors = { p.background, p.error, p.success, p.warning, p.primary,
                   p.secondary, p.accent, p.foreground }
  for index, color in ipairs(colors) do
    vim.g['terminal_color_' .. (index - 1)] = color
    vim.g['terminal_color_' .. (index + 7)] = color
  end
end
